banned_words = [
    "nigger",
    "n word",
    "fag",
    "faggot",
    "beaner",
    "black cock",
    "coon",
    "coons",
    "rape",
    "child porn",
    "child pornography",
    "porno",
    "pornography",
    "jailbait",
    "kike",
    "negro",
    "nig nog",
    "nigga",
    "slanteye",
    "towelhead",
    "porch monkey",
    "sand monkey", 
    "wetback",
    "peeingotter",
    # add any additional banned words here
]